# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: [self-hosted, linux]
    defaults:
      run:
        working-directory: nodeapp

    steps:
    - uses: actions/checkout@main
    - run: npm ci
    - run: npm run build --if-present
